name: FLUTTER CI/CD Workflow

on:
  push:
    branches:
      - main
      - release/*
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      # Explicitly set Flutter in PATH after installation
      - name: Add Flutter to PATH
        run: echo "${{ runner.tool_cache }}/flutter/bin" >> $GITHUB_PATH

      # Confirm Flutter installation path and check if it’s recognized
      - name: Show Flutter installation path
        run: |
          echo $PATH
          which flutter || echo "Flutter not found in PATH"

      # Verify Flutter installation
      - name: Verify Flutter installation
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build APK
        run: flutter build apk --release
        env:
          FLUTTER_ENV: production

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk


  #     - name: Upload APK artifact
  #       if: always()
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: release-apk
  #         path: build/app/outputs/flutter-apk/app-release.apk


  # test:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Run unit tests
  #       run: flutter test

  #     - name: Run integration tests
  #       run: flutter drive --target=test_driver/app.dart

#   deploy:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
#     needs: [build, test]
#     steps:
#       - name: Deploy to Firebase App Distribution
#         uses: wzieba/Firebase-Distribution-Github-Action@v1
#         with:
#           appId: ${{ secrets.FIREBASE_APP_ID }}
#           token: ${{ secrets.FIREBASE_TOKEN }}
#           groups: testers
#           file: build/app/outputs/flutter-apk/app-release.apk

# notifications:
#   slack:
#     if: failure()
#     uses: rtCamp/action-slack-notify@v2
#     with:
#       status: ${{ job.status }}
#       webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
