name: FLUTTER CI/CD Workflow

on:
  push:
    branches:
      - main
      - release/*
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      # Ensure the flutter binary is in PATH
      - name: Add Flutter to PATH
        run: echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH

      # Confirm Flutter installation path
      - name: Show Flutter installation path
        run: which flutter

      # Verify Flutter installation
      - name: Verify Flutter installation
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Cache Pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Limpiar proyecto
        run: flutter clean
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
        env:
          FLUTTER_ENV: production

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk


  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Install GTK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Clean project
        run: flutter clean
      # - name: Analyze code
      #   run: flutter analyze
      - name: Run Flutter tests with retry logic
        run: |
          for i in {1..3}; do
            flutter drive --target=test_driver/app.dart -d linux && break || echo "Retrying..."
            sleep 5
          done


  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting



  notify-email:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Send Notification via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Pipeline Result: ${{ job.status }}"
          body: |
            El pipeline ha completado su ejecución.

            Workflow: ${{ github.workflow }}
            Job Status: ${{ job.status }}
            Event: ${{ github.event_name }}
            Repository: ${{ github.repository }}
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: ${{ secrets.MAIL_USERNAME }}